spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bible?serverTimezone=America/Chicago
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:MapperConfig.xml
  mapper-locations: classpath*:/mappers/*.xml
